'use strict';

const path = require('node:path');

// Generated by scripts/generate-brand.ts. Native QR dependencies are linked
// only when the brand includes the qr-login plugin.
module.exports = {
  dependencies: {
    ...(process.platform === 'win32'
      ? {
          'react-native-safe-area-context': {
            platforms: {
              android: {
                cmakeListsPath: path
                  .join(
                    __dirname,
                    'android/cmake/react-native-safe-area-context/CMakeLists.txt',
                  )
                  .replace(/\\/g, '/'),
              },
            },
          },
        }
      : {}),

  },
};
