import { paymentFlowTranslations } from './flowTranslations';

export const paymentsTranslations = {
  'zh-CN': {
    ...paymentFlowTranslations['zh-CN'],
    'commerce.payment.provider.wechat': '微信支付',
    'commerce.payment.provider.wechat.short': '微信',
    'commerce.payment.provider.wechat.mark': '微',
    'commerce.payment.provider.alipay': '支付宝支付',
    'commerce.payment.provider.alipay.short': '支付宝',
    'commerce.payment.provider.alipay.mark': '支',
    'commerce.payment.creating': '正在创建安全支付订单…',
    'commerce.payment.returnToApp':
      '完成支付后请返回本应用，我们会自动确认结果。',
    'commerce.payment.statusCheckFailed':
      '暂时无法确认结果，请稍后重试；请勿重复支付。',
    'commerce.payment.cancelled': '支付已取消，你可以重新发起。',
    'commerce.payment.failed': '支付失败，请重试。',
    'commerce.payment.pending':
      '支付平台仍在处理中，请稍后再次查询；请勿重复支付。',
    'commerce.payment.processing': '处理中…',
    'commerce.payment.payWith': '使用{provider}支付',
    'commerce.payment.check.accessibilityLabel': '查询支付结果',
    'commerce.payment.check.label': '我已完成支付，查询结果',
    'commerce.payment.securityNote':
      '支付签名由服务端生成，客户端不会保存商户私钥。支付结果以服务端查询为准。',
    'commerce.payment.success.title': '支付成功',
    'commerce.payment.success.description':
      '订单已支付，我们会尽快为你安排发货。',
    'commerce.payment.success.action': '继续购物',
    'commerce.payment.error.authenticationRequired':
      '登录状态已失效，请重新登录后支付。',
    'commerce.payment.error.launchFailed': '暂时无法发起支付，请稍后重试。',
    'commerce.payment.error.wechatUnavailable':
      '无法打开微信，请确认已安装并升级到最新版',
    'commerce.payment.error.alipayUnavailable':
      '无法打开支付宝，请确认已安装并升级到最新版',
    'commerce.payment.error.invalidUrl': '支付地址格式无效',
    'commerce.payment.error.untrustedUrl': '支付地址不属于受信任的支付平台',
    'commerce.payment.error.providerMismatch': '支付地址与所选支付方式不匹配',
  },
  'en-US': {
    ...paymentFlowTranslations['en-US'],
    'commerce.payment.provider.wechat': 'WeChat Pay',
    'commerce.payment.provider.wechat.short': 'WeChat',
    'commerce.payment.provider.wechat.mark': 'W',
    'commerce.payment.provider.alipay': 'Alipay',
    'commerce.payment.provider.alipay.short': 'Alipay',
    'commerce.payment.provider.alipay.mark': 'A',
    'commerce.payment.creating': 'Creating a secure payment order…',
    'commerce.payment.returnToApp':
      'Return to this app after payment. We will confirm the result automatically.',
    'commerce.payment.statusCheckFailed':
      'We cannot confirm the result right now. Try again later and do not pay twice.',
    'commerce.payment.cancelled':
      'Payment was cancelled. You can start it again.',
    'commerce.payment.failed': 'Payment failed. Please try again.',
    'commerce.payment.pending':
      'The payment provider is still processing. Check again later and do not pay twice.',
    'commerce.payment.processing': 'Processing…',
    'commerce.payment.payWith': 'Pay with {provider}',
    'commerce.payment.check.accessibilityLabel': 'Check payment result',
    'commerce.payment.check.label': 'I have paid. Check the result',
    'commerce.payment.securityNote':
      'Payment signatures are generated by the server. Merchant private keys are never stored on this device, and the server result is authoritative.',
    'commerce.payment.success.title': 'Payment successful',
    'commerce.payment.success.description':
      'Your order is paid. We will arrange shipment as soon as possible.',
    'commerce.payment.success.action': 'Continue shopping',
    'commerce.payment.error.authenticationRequired':
      'Your session has expired. Sign in again to pay.',
    'commerce.payment.error.launchFailed':
      'Unable to start payment right now. Please try again later.',
    'commerce.payment.error.wechatUnavailable':
      'Unable to open WeChat. Make sure it is installed and up to date.',
    'commerce.payment.error.alipayUnavailable':
      'Unable to open Alipay. Make sure it is installed and up to date.',
    'commerce.payment.error.invalidUrl': 'The payment URL is invalid.',
    'commerce.payment.error.untrustedUrl':
      'The payment URL is not from a trusted payment provider.',
    'commerce.payment.error.providerMismatch':
      'The payment URL does not match the selected payment method.',
  },
};
