import fs from 'node:fs';
import path from 'node:path';
import {
  escapeXml,
  MODULES,
  readBrand,
  ROOT,
  validateBrand,
} from './brand-utils';

const cliBrand = process.argv.slice(2).find(value => !value.startsWith('--'));
const brandId = cliBrand || process.env.BRAND || 'aurora';
const { config: brand } = readBrand(brandId);
const errors = validateBrand(brand);
if (errors.length) {
  throw new Error(`Invalid brand "${brandId}":\n- ${errors.join('\n- ')}`);
}
const hasQrLogin = brand.assembly.modules.includes('qr-login');

function write(relativePath: string, contents: string): void {
  const target = path.join(ROOT, relativePath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(
    target,
    contents.endsWith('\n') ? contents : `${contents}\n`,
  );
}

const moduleImports = brand.assembly.modules.map(id => {
  const moduleDefinition = MODULES[id];
  if (!moduleDefinition) {
    throw new Error(`Unknown module "${id}"`);
  }
  return moduleDefinition;
});
const activeBrandSource = `// Generated by scripts/generate-brand.ts. Do not edit manually.
import rawBrand from '../../../brands/${brand.id}/brand.config.json';
${moduleImports
  .map(module => `import {${module.symbol}} from '${module.importPath}';`)
  .join('\n')}
import type {BrandConfig} from '../../brand/types';

export const activeBrand = rawBrand as BrandConfig;
export const activeModuleFactories = [
${moduleImports.map(module => `  ${module.symbol},`).join('\n')}
];
`;
write('src/brands/generated/activeBrand.ts', activeBrandSource);

const qrNativeDependencies = [
  'react-native-nitro-image',
  'react-native-nitro-modules',
  'react-native-vision-camera',
  'react-native-vision-camera-barcode-scanner',
];
const disabledNativeDependencies = hasQrLogin
  ? ''
  : qrNativeDependencies
      .map(name => `    '${name}': {platforms: {android: null, ios: null}},`)
      .join('\n');
write(
  'react-native.config.js',
  `'use strict';

// Generated by scripts/generate-brand.ts. Native QR dependencies are linked
// only when the brand includes the qr-login plugin.
module.exports = {
  dependencies: {
${disabledNativeDependencies}
  },
};`,
);

write(
  'app.json',
  JSON.stringify(
    { name: 'WhiteLabelApp', displayName: brand.appName },
    null,
    2,
  ),
);

write(
  'generated/native/android.properties',
  [
    '# Generated. Secrets must come from CI environment variables.',
    `brandId=${brand.id}`,
    `applicationId=${brand.native.android.applicationId}`,
    `appName=${brand.appName}`,
    `deepLinkScheme=${brand.native.deepLinks.scheme}`,
    `deepLinkHost=${brand.native.deepLinks.hosts[0]}`,
    `channelId=${brand.native.channel.id}`,
    `keystorePath=${brand.native.android.keystorePath || ''}`,
    `keyAlias=${brand.native.android.keyAlias || ''}`,
  ].join('\n'),
);

write(
  'generated/native/BrandConfig.xcconfig',
  [
    '// Generated. Include from the CI/Xcode build configuration when required.',
    `PRODUCT_BUNDLE_IDENTIFIER = ${brand.native.ios.bundleId}`,
    `DEVELOPMENT_TEAM = ${brand.native.ios.teamId || ''}`,
    `PROVISIONING_PROFILE_SPECIFIER = ${
      brand.native.ios.provisioningProfile || ''
    }`,
    `BRAND_CHANNEL_ID = ${brand.native.channel.id}`,
  ].join('\n'),
);

const stringsPath = path.join(
  ROOT,
  'android/app/src/main/res/values/strings.xml',
);
fs.writeFileSync(
  stringsPath,
  `<resources>\n    <string name="app_name">${escapeXml(
    brand.appName,
  )}</string>\n</resources>\n`,
);

const androidManifestPath = path.join(
  ROOT,
  'android/app/src/main/AndroidManifest.xml',
);
let androidManifest = fs
  .readFileSync(androidManifestPath, 'utf8')
  .replace(
    /\s*<uses-permission android:name="android\.permission\.(?:CAMERA|VIBRATE)"\s*\/>/g,
    '',
  );
if (hasQrLogin) {
  androidManifest = androidManifest.replace(
    /(<uses-permission android:name="android\.permission\.INTERNET"\s*\/>)/,
    '$1\n    <uses-permission android:name="android.permission.CAMERA" />\n    <uses-permission android:name="android.permission.VIBRATE" />',
  );
}
fs.writeFileSync(androidManifestPath, androidManifest);

const projectPath = path.join(
  ROOT,
  'ios/WhiteLabelApp.xcodeproj/project.pbxproj',
);
let project = fs.readFileSync(projectPath, 'utf8');
project = project
  .replace(/\s*DEVELOPMENT_TEAM = [^;]*;/g, '')
  .replace(/\s*PROVISIONING_PROFILE_SPECIFIER = [^;]*;/g, '');
project = project.replace(
  /PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/g,
  () =>
    `PRODUCT_BUNDLE_IDENTIFIER = "${brand.native.ios.bundleId}";${
      brand.native.ios.teamId
        ? `\n\t\t\t\tDEVELOPMENT_TEAM = "${brand.native.ios.teamId}";`
        : ''
    }` +
    `${
      brand.native.ios.provisioningProfile
        ? `\n\t\t\t\tPROVISIONING_PROFILE_SPECIFIER = "${brand.native.ios.provisioningProfile}";`
        : ''
    }`,
);
fs.writeFileSync(projectPath, project);

const infoPath = path.join(ROOT, 'ios/WhiteLabelApp/Info.plist');
let info = fs.readFileSync(infoPath, 'utf8');
info = info.replace(
  /(<key>CFBundleDisplayName<\/key>\s*<string>)[^<]*(<\/string>)/,
  `$1${escapeXml(brand.appName)}$2`,
);
info = info.replace(
  /(<key>CFBundleURLSchemes<\/key>\s*<array>\s*<string>)[^<]*(<\/string>)/,
  `$1${escapeXml(brand.native.deepLinks.scheme)}$2`,
);
info = info.replace(
  /\s*<key>NSCameraUsageDescription<\/key>\s*<string>[^<]*<\/string>/,
  '',
);
if (hasQrLogin) {
  info = info.replace(
    /\n<\/dict>\s*<\/plist>\s*$/,
    `\n\t<key>NSCameraUsageDescription</key>\n\t<string>${escapeXml(
      brand.native.permissions.cameraUsage,
    )}</string>\n</dict>\n</plist>\n`,
  );
}
fs.writeFileSync(infoPath, info);

write(
  'generated/native/brand-manifest.json',
  JSON.stringify(
    {
      brandId: brand.id,
      appName: brand.appName,
      modules: brand.assembly.modules,
      ios: brand.native.ios,
      android: brand.native.android,
      deepLinks: brand.native.deepLinks,
      push: brand.native.push,
      channel: brand.native.channel,
      sdkKeyNames: Object.keys(brand.native.sdkKeys),
    },
    null,
    2,
  ),
);

console.log(`Generated native and TypeScript entries for ${brand.id}`);
