import fs from 'node:fs';
import path from 'node:path';
import type { BrandEnvironmentName } from '../src/brand/types';
import {
  escapeXml,
  escapePropertiesValue,
  MODULES,
  readBrand,
  ROOT,
  validateBrand,
} from './brand-utils';

const ENVIRONMENTS: BrandEnvironmentName[] = [
  'development',
  'staging',
  'production',
];

interface PackageManifest {
  version: string;
}

export interface GenerateBrandOptions {
  brandId: string;
  environment: BrandEnvironmentName;
  versionName: string;
  buildNumber: number;
}

function packageVersion(): string {
  const manifest = JSON.parse(
    fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'),
  ) as PackageManifest;
  return manifest.version;
}

function optionValue(args: string[], index: number, name: string): string {
  const value = args[index + 1];
  if (!value || value.startsWith('--')) {
    throw new Error(`${name} requires a value`);
  }
  return value;
}

export function parseGenerateBrandOptions(
  args: string[],
  env: NodeJS.ProcessEnv = process.env,
): GenerateBrandOptions {
  let brandId = env.BRAND || 'aurora';
  let environment = env.APP_ENV || 'development';
  let versionName = env.APP_VERSION || packageVersion();
  let buildNumber = env.BUILD_NUMBER || '1';
  let positionalBrandSeen = false;

  for (let index = 0; index < args.length; index += 1) {
    const argument = args[index];
    if (argument === '--environment' || argument === '--env') {
      environment = optionValue(args, index, argument);
      index += 1;
    } else if (argument.startsWith('--environment=')) {
      environment = argument.slice('--environment='.length);
    } else if (argument.startsWith('--env=')) {
      environment = argument.slice('--env='.length);
    } else if (argument === '--version-name' || argument === '--version') {
      versionName = optionValue(args, index, argument);
      index += 1;
    } else if (argument.startsWith('--version-name=')) {
      versionName = argument.slice('--version-name='.length);
    } else if (argument.startsWith('--version=')) {
      versionName = argument.slice('--version='.length);
    } else if (argument === '--build-number') {
      buildNumber = optionValue(args, index, argument);
      index += 1;
    } else if (argument.startsWith('--build-number=')) {
      buildNumber = argument.slice('--build-number='.length);
    } else if (argument.startsWith('--')) {
      throw new Error(`Unknown option: ${argument}`);
    } else if (!positionalBrandSeen) {
      brandId = argument;
      positionalBrandSeen = true;
    } else {
      throw new Error(`Unexpected argument: ${argument}`);
    }
  }

  if (!ENVIRONMENTS.includes(environment as BrandEnvironmentName)) {
    throw new Error(
      `Invalid environment "${environment}". Expected: ${ENVIRONMENTS.join(
        ', ',
      )}`,
    );
  }
  if (!/^\d+(?:\.\d+){0,2}$/.test(versionName)) {
    throw new Error(
      `Invalid version "${versionName}". Use a value such as 1.2.3.`,
    );
  }
  if (!/^\d+$/.test(buildNumber) || Number(buildNumber) < 1) {
    throw new Error('Build number must be a positive integer.');
  }

  return {
    brandId,
    environment: environment as BrandEnvironmentName,
    versionName,
    buildNumber: Number(buildNumber),
  };
}

export function generateBrand(options: GenerateBrandOptions): void {
  const { brandId, environment, versionName, buildNumber } = options;
  const { config: brand } = readBrand(brandId);
  const errors = validateBrand(brand);
  if (brand.id !== brandId) {
    errors.unshift(`config id must match directory name "${brandId}"`);
  }
  if (errors.length) {
    throw new Error(`Invalid brand "${brandId}":\n- ${errors.join('\n- ')}`);
  }
  const hasQrLogin = brand.assembly.modules.includes('qr-login');
  const hasCommerce = brand.assembly.modules.includes('commerce');

  function write(relativePath: string, contents: string): void {
    const target = path.join(ROOT, relativePath);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(
      target,
      contents.endsWith('\n') ? contents : `${contents}\n`,
    );
  }

  const moduleImports = brand.assembly.modules.map(id => {
    const moduleDefinition = MODULES[id];
    if (!moduleDefinition) {
      throw new Error(`Unknown module "${id}"`);
    }
    return moduleDefinition;
  });
  const activeBrandSource = `// Generated by scripts/generate-brand.ts. Do not edit manually.
import rawBrand from '../../../brands/${brand.id}/brand.config.json';
${moduleImports
  .map(module => `import {${module.symbol}} from '${module.importPath}';`)
  .join('\n')}
import type {BrandConfig} from '../../brand/types';

export const activeBrand = rawBrand as BrandConfig;
export const activeEnvironment = '${environment}' as const;
export const activeVersionName = '${versionName}';
export const activeBuildNumber = ${buildNumber};
export const activeModuleFactories = [
${moduleImports.map(module => `  ${module.symbol},`).join('\n')}
];
`;
  write('src/brands/generated/activeBrand.ts', activeBrandSource);

  const qrNativeDependencies = [
    'react-native-nitro-image',
    'react-native-nitro-modules',
    'react-native-vision-camera',
    'react-native-vision-camera-barcode-scanner',
  ];
  const disabledNativeDependencies = hasQrLogin
    ? ''
    : qrNativeDependencies
        .map(name => `    '${name}': {platforms: {android: null, ios: null}},`)
        .join('\n');
  write(
    'react-native.config.js',
    `'use strict';

const path = require('node:path');

// Generated by scripts/generate-brand.ts. Native QR dependencies are linked
// only when the brand includes the qr-login plugin.
module.exports = {
  dependencies: {
    ...(process.platform === 'win32'
      ? {
          'react-native-safe-area-context': {
            platforms: {
              android: {
                cmakeListsPath: path
                  .join(
                    __dirname,
                    'android/cmake/react-native-safe-area-context/CMakeLists.txt',
                  )
                  .replace(/\\\\/g, '/'),
              },
            },
          },
        }
      : {}),
${disabledNativeDependencies}
  },
};`,
  );

  write(
    'app.json',
    JSON.stringify(
      { name: 'WhiteLabelApp', displayName: brand.appName },
      null,
      2,
    ),
  );

  write(
    'generated/native/android.properties',
    [
      '# Generated. Secrets must come from CI environment variables.',
      `brandId=${brand.id}`,
      `environment=${environment}`,
      `versionName=${versionName}`,
      `versionCode=${buildNumber}`,
      `applicationId=${brand.native.android.applicationId}`,
      `appName=${brand.appName}`,
      `deepLinkScheme=${brand.native.deepLinks.scheme}`,
      `deepLinkHost=${brand.native.deepLinks.hosts[0]}`,
      `channelId=${brand.native.channel.id}`,
      `keystorePath=${escapePropertiesValue(
        brand.native.android.keystorePath || '',
      )}`,
      `keyAlias=${escapePropertiesValue(brand.native.android.keyAlias || '')}`,
    ].join('\n'),
  );

  write(
    'generated/native/BrandConfig.xcconfig',
    [
      '// Generated. The packaging command also passes these values to xcodebuild.',
      `PRODUCT_BUNDLE_IDENTIFIER = ${brand.native.ios.bundleId}`,
      `DEVELOPMENT_TEAM = ${brand.native.ios.teamId || ''}`,
      `PROVISIONING_PROFILE_SPECIFIER = ${
        brand.native.ios.provisioningProfile || ''
      }`,
      `MARKETING_VERSION = ${versionName}`,
      `CURRENT_PROJECT_VERSION = ${buildNumber}`,
      `BRAND_ENVIRONMENT = ${environment}`,
      `BRAND_CHANNEL_ID = ${brand.native.channel.id}`,
    ].join('\n'),
  );

  const stringsPath = path.join(
    ROOT,
    'android/app/src/main/res/values/strings.xml',
  );
  fs.writeFileSync(
    stringsPath,
    `<resources>\n    <string name="app_name">${escapeXml(
      brand.appName,
    )}</string>\n</resources>\n`,
  );

  const androidManifestPath = path.join(
    ROOT,
    'android/app/src/main/AndroidManifest.xml',
  );
  let androidManifest = fs
    .readFileSync(androidManifestPath, 'utf8')
    .replace(
      /\s*<uses-permission android:name="android\.permission\.(?:CAMERA|VIBRATE)"\s*\/>/g,
      '',
    )
    .replace(
      /\s*<!-- commerce-payment-queries:start -->[\s\S]*?<!-- commerce-payment-queries:end -->/g,
      '',
    );
  if (hasQrLogin) {
    androidManifest = androidManifest.replace(
      /(<uses-permission android:name="android\.permission\.INTERNET"\s*\/>)/,
      '$1\n    <uses-permission android:name="android.permission.CAMERA" />\n    <uses-permission android:name="android.permission.VIBRATE" />',
    );
  }
  if (hasCommerce) {
    androidManifest = androidManifest.replace(
      /(<manifest[^>]*>)/,
      `$1

    <!-- commerce-payment-queries:start -->
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="alipays" />
        </intent>
    </queries>
    <!-- commerce-payment-queries:end -->`,
    );
  }
  fs.writeFileSync(androidManifestPath, androidManifest);

  const projectPath = path.join(
    ROOT,
    'ios/WhiteLabelApp.xcodeproj/project.pbxproj',
  );
  let project = fs.readFileSync(projectPath, 'utf8');
  project = project
    .replace(/\s*DEVELOPMENT_TEAM = [^;]*;/g, '')
    .replace(/\s*PROVISIONING_PROFILE_SPECIFIER = [^;]*;/g, '');
  project = project.replace(
    /PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/g,
    () =>
      `PRODUCT_BUNDLE_IDENTIFIER = "${brand.native.ios.bundleId}";${
        brand.native.ios.teamId
          ? `\n\t\t\t\tDEVELOPMENT_TEAM = "${brand.native.ios.teamId}";`
          : ''
      }${
        brand.native.ios.provisioningProfile
          ? `\n\t\t\t\tPROVISIONING_PROFILE_SPECIFIER = "${brand.native.ios.provisioningProfile}";`
          : ''
      }`,
  );
  project = project
    .replace(
      /CURRENT_PROJECT_VERSION = [^;]+;/g,
      `CURRENT_PROJECT_VERSION = ${buildNumber};`,
    )
    .replace(
      /MARKETING_VERSION = [^;]+;/g,
      `MARKETING_VERSION = ${versionName};`,
    );
  fs.writeFileSync(projectPath, project);

  const infoPath = path.join(ROOT, 'ios/WhiteLabelApp/Info.plist');
  let info = fs.readFileSync(infoPath, 'utf8');
  info = info.replace(
    /(<key>CFBundleDisplayName<\/key>\s*<string>)[^<]*(<\/string>)/,
    `$1${escapeXml(brand.appName)}$2`,
  );
  info = info.replace(
    /(<key>CFBundleURLSchemes<\/key>\s*<array>\s*<string>)[^<]*(<\/string>)/,
    `$1${escapeXml(brand.native.deepLinks.scheme)}$2`,
  );
  info = info.replace(
    /\s*<key>NSCameraUsageDescription<\/key>\s*<string>[^<]*<\/string>/,
    '',
  );
  info = info.replace(
    /\s*<!-- commerce-payment-schemes:start -->[\s\S]*?<!-- commerce-payment-schemes:end -->/g,
    '',
  );
  if (hasQrLogin) {
    info = info.replace(
      /\n<\/dict>\s*<\/plist>\s*$/,
      `\n\t<key>NSCameraUsageDescription</key>\n\t<string>${escapeXml(
        brand.native.permissions.cameraUsage,
      )}</string>\n</dict>\n</plist>\n`,
    );
  }
  if (hasCommerce) {
    info = info.replace(
      /\n<\/dict>\s*<\/plist>\s*$/,
      `
\t<!-- commerce-payment-schemes:start -->
\t<key>LSApplicationQueriesSchemes</key>
\t<array>
\t\t<string>alipays</string>
\t</array>
\t<!-- commerce-payment-schemes:end -->
</dict>
</plist>
`,
    );
  }
  fs.writeFileSync(infoPath, info);

  write(
    'generated/native/brand-manifest.json',
    JSON.stringify(
      {
        brandId: brand.id,
        appName: brand.appName,
        environment,
        versionName,
        buildNumber,
        modules: brand.assembly.modules,
        ios: brand.native.ios,
        android: brand.native.android,
        deepLinks: brand.native.deepLinks,
        push: brand.native.push,
        channel: brand.native.channel,
        sdkKeyNames: Object.keys(brand.native.sdkKeys),
      },
      null,
      2,
    ),
  );

  console.log(
    `Generated ${brand.id} (${environment}, ${versionName}+${buildNumber})`,
  );
}

function main(): void {
  generateBrand(parseGenerateBrandOptions(process.argv.slice(2)));
}

if (require.main === module) {
  main();
}
